version: "3.1"

services:
  jenkins:
    build:
      context: ./images
      dockerfile: jenkins.dockerfile
    image: hiramlabs/jenkins
    container_name: jenkins
    restart: unless-stopped
    ports:
      - 9010:8080
      - 9011:50000
    volumes:
      - jenkins_data:/var/jenkins_home

volumes:
  jenkins_data:
