version: "3.1"

services:
  jenkins:
    build:
      context: ./images
      dockerfile: jenkins.dockerfile
    image: hiramlabs/jenkins
    container_name: jenkins
    restart: unless-stopped
    #    ports:
    #      - 9010:8080
    #      - 9011:50000
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - interface
    user: ${__CURRENT_UID_DOCKER_GID}

  vscode:
    build:
      context: ./images
      dockerfile: vscode.dockerfile
    image: hiramlabs/vscode
    container_name: vscode
    restart: unless-stopped
    #    ports:
    #      - 9011:8080
    volumes:
      - vscode_data:/home/coder/project
      - ./volume/vscode:/home/coder/.config
    networks:
      - interface
    user: ${__CURRENT_UID}

volumes:
  jenkins_data:
  vscode_data:

networks:
  interface:
    external:
      name: interface
