#!/bin/sh

__ARG=$1

__START_DOCKER_COMPOSE="start"
__STOP_DOCKER_COMPOSE="stop"

__START_JENKINS_SHELL="jkn:shell"
__START_VSCODE_SHELL="vsc:shell"

__CURRENT_UID=$(id -u):$(id -g)
__CURRENT_UID_DOCKER_GID=$(id -u):$(getent group docker | cut -d: -f3)

export __CURRENT_UID
export __CURRENT_UID_DOCKER_GID

if [[ "$__ARG" == "$__START_DOCKER_COMPOSE" ]]; then
    shift
    docker-compose up -d "$@"
fi

if [[ "$__ARG" == "$__STOP_DOCKER_COMPOSE" ]]; then
    shift
    docker-compose down "$@"
fi

if [[ "$__ARG" == "$__START_JENKINS_SHELL" ]]; then
    docker exec -it jenkins /bin/bash --login
fi

if [[ "$__ARG" == "$__START_VSCODE_SHELL" ]]; then
    docker exec -it vscode /bin/bash --login
fi
